const express = require('express');
const authRoutes = require('./auth');
const userRoutes = require('./users');
const postRoutes = require('./posts');
const commentRoutes = require('./comments');
const likeRoutes = require('./likes');
const followRoutes = require('./follows');
const messageRoutes = require('./messages');
const storyRoutes = require('./stories');
const notificationRoutes = require('./notifications');
const uploadRoutes = require('./uploads');
const reportRoutes = require('./reports');
const callRoutes = require('./calls');
const adminRoutes = require('./admin');
const feedbackRoutes = require('./feedback');
const appRoutes = require('./app');
const trendRoutes = require('./trends');
const youtubeNewsRoutes = require('./youtubeNews');
const reelsRoutes = require('./reels');
const groupsRoutes = require('./groups');
const stickerRoutes = require('./stickers');

const router = express.Router();

router.use('/', authRoutes);
router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/users', userRoutes);
router.use('/posts', postRoutes);
router.use('/comments', commentRoutes);
router.use('/likes', likeRoutes);
router.use('/follows', followRoutes);
router.use('/messages', messageRoutes);
router.use('/stories', storyRoutes);
router.use('/notifications', notificationRoutes);
router.use('/uploads', uploadRoutes);
router.use('/reports', reportRoutes);
router.use('/calls', callRoutes);
router.use('/admin', adminRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/feedbacks', feedbackRoutes);
router.use('/app', appRoutes);
router.use('/trends', trendRoutes);
router.use('/youtube-news', youtubeNewsRoutes);
router.use('/reels', reelsRoutes);
router.use('/groups', groupsRoutes);
router.use('/stickers', stickerRoutes);

module.exports = router;